Tips/Tips/urls.py
from django.contrib import admin
from django.urls import path,include
from diaxoristis import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.IndexView.as_view()),
    path('diaxoristis/',include('diaxoristis.urls',namespace='diaxoristis')),
]

Tips/diaxoristis/level_four/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
        path("relative/",views.relative,name='relative'),
        path("other/",views.other,name="other"),
]

Tips/diaxoristis/level_four/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name= 'index'),
    path('basic_app/',include('basic_app.urls'))
]

Tips/diaxoristis/urls.py
from django.urls  import path,re_path
from diaxoristis import views

app_name = 'diaxoristis'

urlpatterns = [
    path("",views.IndexView.as_view(),name = 'index'),
    path("about/",views.AboutView.as_view(),name = 'about'),

    path("list_employee/",views.EmployeeListView.as_view(),name = 'employee_list'),
    path('list_employee/<int:pk>/',views.EmployeeDetailView.as_view(),name = 'employee_detail'),
    path("create_employee/",views.EmployeeCreateView.as_view(),name = "employee_create"),
    re_path('update_employee/(?P<pk>\d+)/',views.EmployeeUpdateView.as_view(),name = 'employee_update'),
    re_path('delete_employee/(?P<pk>\d+)/',views.EmployeeDeleteView.as_view(),name = 'employee_delete'),

    path("list_posto/",views.PostoListView.as_view(),name = 'posto_list'),
    path('list_posto/<int:pk>/',views.PostoDetailView.as_view(),name = 'posto_detail'),
    path("create_posto/",views.PostoCreateView.as_view(),name = "posto_create"),
    re_path('update_posto/(?P<pk>\d+)/',views.PostoUpdateView.as_view(),name = 'posto_update'),
    re_path('delete_posto/(?P<pk>\d+)/',views.PostoDeleteView.as_view(),name = 'posto_delete'),

    path("list_tip/",views.TipListView.as_view(),name = 'tip_list'),
    path('list_tip/<int:pk>/',views.TipDetailView.as_view(),name = 'tip_detail'),
    re_path('delete_tip/(?P<pk>\d+)/',views.TipDeleteView.as_view(),name = 'tip_delete'),

    path("step_one/",views.StepOneView.as_view(),name = 'step_one'),
    path("step_two/",views.StepTwoView.as_view(),name = 'step_two'),
    path("step_three/",views.StepThreeView,name = 'step_three'),

    path("step_three/saved/",views.SavedView.as_view(),name = "saved"),
]

Tips/diaxoristis/level_four/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Tips/diaxoristis/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.urls import reverse

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=256)
    parts = models.IntegerField()

    def get_absolute_url(self):
        return reverse('employee_list')

    def __str__(self):
        return self.name

class Posto(models.Model):
    name = models.CharField(max_length=256)

    def get_absolute_url(self):
        return reverse('posto_list')

    def __str__(self):
        return self.name


class Tip(models.Model):
    posto = models.ForeignKey('diaxoristis.Posto',related_name = 'tips',on_delete = 'CASCADE')
    start_date =models.DateField()
    end_date = models.DateField()
    money = models.FloatField()

    def get_absolute_url(self):
        return reverse('tip_list')

    def __str__(self):
        formatedDate = self.start_date.strftime("%d-%m-%Y")
        return str(formatedDate)

Tips/diaxoristis/forms.py
from django import forms
from diaxoristis.models import Posto,Employee,Tip
from . import app_settings


class EmployeeForm(forms.Form):

    class Meta():
        model = Employee
        fields = ('name','parts')
        labels = {
            "name":"Όνομα",
            "parts":"Μέρη"
            }

class PostoForm(forms.Form):

    class Meta():
        model = Posto
        fields = ("name",)
        labels = {
            "name":"Όνομα"
        }


class TipForm(forms.Form):

    class Meta():
        model = Tip
        fields = ('posto','money','start_date','end_date')

class StepOneEmployeeForm(forms.Form):

    employees = forms.ModelMultipleChoiceField(
        queryset = Employee.objects.all(), # or .filter(…) if you want only some articles to show up
        widget  = forms.CheckboxSelectMultiple,label = "Διάλεξε Υπαλλήλους:"
    )

    posta = forms.ModelChoiceField ( queryset = Posto.objects.all(), widget= forms.Select,label = "Διάλεξε πόστο:")


class StepTwoEmployeeForm(forms.Form):
    money = forms.FloatField(label = "Χρήματα:")
    date_from=forms.DateField(input_formats = app_settings.DATE_INPUT_FORMATS,label = "Από:")
    date_until=forms.DateField(input_formats = app_settings.DATE_INPUT_FORMATS,label = "Μέχρι:")


    def __init__(self, *args, **kwargs):
        extra=app_settings.MyEmployees



        super(StepTwoEmployeeForm,self).__init__(*args, **kwargs)


        if len(extra) !=0 :

            for i in extra:

                for i in extra:
                    self.fields[i.name] = forms.IntegerField(label = i.name)
                    app_settings.Dynamic_Fields.append(i.name)

Tips/diaxoristis/level_four/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,"basic_app/index.html",context= context_dict)

def other(request):
    return render(request,"basic_app/other.html")

def relative(request):
    return render(request,"basic_app/relative_url_templates.html")

Tips/diaxoristis/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django import forms
#from diaxoristis.models import Employee,Posto,Tip
from diaxoristis.forms import (EmployeeForm,PostoForm,TipForm,StepOneEmployeeForm,
                               StepTwoEmployeeForm)
from django.urls import reverse_lazy
from django.views.generic import(TemplateView,ListView,
                                 DetailView,CreateView,UpdateView,
                                 DeleteView,FormView)
from . import models
from . import tipsLib
from . import app_settings

# Create your views here.

class AboutView(TemplateView):
    template_name = 'diaxoristis/about.html'


class IndexView(TemplateView):
    template_name = 'diaxoristis/index.html'

class StepOneView(FormView):
    template_name = 'diaxoristis/step_one.html'
    form_class = StepOneEmployeeForm
    success_url=reverse_lazy('diaxoristis:step_two')



    def form_valid(self, form_class):


        self.get_data(form_class.cleaned_data)
        return super(StepOneView, self).form_valid(form_class)

    def get_data(self, valid_data):
        app_settings.MyPosto = []
        app_settings.MyEmployees = []
        app_settings.Dynamic_Fields=[]
        # Αποθηεκεύουμε το πόστο
        app_settings.MyPosto = valid_data['posta']
        employees =valid_data['employees']
        #πέρνουμε τα object υπαλλήλων και τα αποθηκεύουμε σε λίστα
        for i in employees:
            emp = models.Employee.objects.get(name=i)
            app_settings.MyEmployees.append(emp)



class StepTwoView(FormView):
    template_name = 'diaxoristis/step_two.html'
    form_class=None
    form_class = StepTwoEmployeeForm
    success_url=reverse_lazy('diaxoristis:step_three')




    def form_valid(self, form_class):
        self.execute(form_class.cleaned_data)
        return super(StepTwoView, self).form_valid(form_class)

    def execute(self, valid_data):
        app_settings.Diaxoristis = None
        data = valid_data
        money = data['money']
        date_from = data['date_from']
        date_until = data["date_until"]
        employee_Tip_object = []

        for i in app_settings.MyEmployees:
            days = data[i.name]
            ypallilos = tipsLib.Ypallilos(i.name,i.parts,merokamata= days)
            employee_Tip_object.append(ypallilos)

        posto_Tip_Object = tipsLib.Posto(app_settings.MyPosto)
        tips_Tip_Object = tipsLib.Tips(money,posto_Tip_Object,date_in=date_from,date_out=date_until)
        diaxoristis_Tip_Object = tipsLib.Diaxoristis(employee_Tip_object,tips_Tip_Object)
        app_settings.Diaxoristis = diaxoristis_Tip_Object
        app_settings.Result_Tips = app_settings.Diaxoristis.result()


def StepThreeView(request):
    template_name = 'diaxoristis/step_three.html'
    context ={}
    context['result'] = app_settings.Result_Tips

    def save_Tip():

        posto = models.Posto.objects.get(name=app_settings.Result_Tips["posto"])
        p = models.Tip.objects.create(posto= posto,
                                start_date=app_settings.Result_Tips["date_from"],
                                end_date=app_settings.Result_Tips["date_until"],
                                money=app_settings.Result_Tips["money"])

    if request.GET.get('submit'):

        save_Tip()

    return render(request,template_name,{"context":context})



#class StepThreeView(TemplateView):
#    template_name = 'diaxoristis/step_three.html'
#
#
#    def get_context_data(self, **kwargs):
#        context = super(StepThreeView, self).get_context_data(**kwargs)
#        context['result'] = app_settings.Result_Tips
#
#
#        return context
#
#    def save_Tip(self):
#        p = Person.objects.Tip(posto=app_settings.Result_Tips["posto"],
#                                start_date=app_settings.Result_Tips["date_from"],
#                                end_date=app_settings.Result_Tips["date_until"],
#                                money=app_settings.Result_Tips["money"])
#
#
#    def dispatch(self, request, *args, **kwargs):
#        for key in request.GET:
#            print(key)
#            value = request.GET[key]
#            print(value)
#        return super(StepThreeView, self).dispatch(request, *args, **kwargs)
    #def post(self, request):
        #submitbutton= self.request.POST
        #print(self.request.POST.post(''))
        #if submitbutton:
            #print("apothikeytike")
        #self.save_Tip()
class SavedView(TemplateView):
    template_name = 'diaxoristis/saved.html'

class EmployeeListView(ListView):
    model = models.Employee
    context_object_name = 'employees'

    def get_queryset(self):
        return models.Employee.objects.order_by('name')

class EmployeeDetailView(DetailView):
    context_object_name = 'employees_detail'
    model = models.Employee
    template_name = 'diaxoristis/employee_detail.html'

class EmployeeCreateView(CreateView):
    fields = ('name','parts')
    model = models.Employee
    success_url = reverse_lazy("diaxoristis:employee_list")

class EmployeeUpdateView(UpdateView):
    fields = ('name','parts')
    model = models.Employee
    success_url = reverse_lazy("diaxoristis:employee_list")

class EmployeeDeleteView(DeleteView):
    model = models.Employee
    success_url = reverse_lazy("diaxoristis:employee_list")

class PostoListView(ListView):
    context_object_name = 'posta'
    model = models.Posto

    def get_queryset(self):
        return models.Posto.objects.order_by('name')

class PostoDetailView(DetailView):
    context_object_name = 'posto_detail'
    model = models.Posto
    template_name = 'diaxoristis/posto_detail.html'

class PostoCreateView(CreateView):
    fields = ('name',)
    model = models.Posto
    success_url = reverse_lazy("diaxoristis:posto_list")

class PostoUpdateView(UpdateView):
    fields = ('name',)
    model = models.Posto
    success_url = reverse_lazy("diaxoristis:posto_list")

class PostoDeleteView(DeleteView):
    model = models.Posto
    success_url = reverse_lazy("diaxoristis:posto_list")


class TipListView(ListView):
    context_object_name = 'tips'
    model = models.Tip

class TipDetailView(DetailView):
    context_object_name = 'tips_detail'
    model = models.Tip
    template_name = 'diaxoristis/tip_detail.html'

class TipDeleteView(DeleteView):
    model = models.Tip
    success_url = reverse_lazy("diaxoristis:tip_list")

Tips/diaxoristis/templates/diaxoristis/about.html
{% extends "base.html" %}
{% block body_block%}


<h1>
ABOUT ME
</h1>





{% endblock %}

Tips/diaxoristis/templates/diaxoristis/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <title>Tips</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
  </head>
  <body>
    <nav class='navbar navbar-inverse navbar-statick-top nav-color'>
      <ul class='nav navbar-nav '>
        <a class="navbar-brand glyphicon glyphicon-piggy-bank eikona" href="#"></a>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:index' %}">Αρχική</a></li>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:employee_list' %}">Υπάλληλοι</a></li>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:posto_list' %}">Πόστα</a></li>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:tip_list' %}">Tips</a></li>
      </ul>

    </nav>


<div class="container">

  {% block body_block %}
  {% endblock %}

</div>




  </body>
</html>

Tips/diaxoristis/templates/diaxoristis/employee_detail.html
{% extends "base.html" %}
{% block body_block%}
<div class="jumbotron">
  <h1>Detail Page!</h1>


  <div class="container">


  <div class="row">
    <table class="table table-bordered table table-hover">
      <tr>
        <col width="150">
        <col width="600">
        <th><h2>Όνομα</h2></th>
        <td><h3><a href="#">{{employees_detail.name}}</a></h3></td>
      </tr>
      <tr>
        <th><h2>Μέρη</h2></th>
        <td><h3><a href="#">{{employees_detail.parts}}</a></h3></td>
      </tr>

    </table>

  </div>
  </div>


<div class="container">
  <p><a class= 'btn btn-success' href="{% url 'diaxoristis:employee_list' %}">Πίσω</a>

  </p>

</div>
{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/employee_list.html
{% extends "base.html" %}

{% block body_block%}

<div class="jumbotron">

<div class=" container ">
  <div class="row ">
    <h1 class='kentro'>Λίστα Υπαλλήλων</h1>
  </div>

</div>

<div class="container">



<div class="row">
  <table class="table table-bordered table table-hover" >
    <tr>
      <col width="150">
      <col width="150">
      <col width="600">
      <th><h2>Όνομα</h2></th>
      <th><h2>Μέρη</h2></th>
      <th width="600">                                 </th>

    </tr>



    {% for employee in employees %}

      <tr>
        <td><a class="col-md-8" href="{{employee.id}}"><h3>{{employee.name}}</h3></a></td>
        <td><h3>{{employee.parts}}</h3></td>
        <td  width="1000">
      <h2><a class= 'btn btn-warning' href="{% url 'diaxoristis:employee_update' pk=employee.id %}">Επεξεργασία</a>

      <a class= 'btn btn-danger' href="{% url 'diaxoristis:employee_delete' pk=employee.id %}">Διαγαφή</a></h2>
        </td></tr>
    {% endfor %}
  </table>

  <div class="row">
    <div class="col-xs-6 col-md-4">
        <h2><a class= 'btn btn-success' href="{% url 'diaxoristis:employee_create' %}">Δημιουργία</a></h2>
    </div>
    <div class="col-xs-6 col-md-4"></div>
    <div class="col-xs-6 col-md-4">

    </div>
  </div>
</div>


</div>

{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <title>Tips</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

    <link rel="stylesheet" href="{% static '/css/main.css' %}">
  </head>
  <body class="bg">
    <nav class='navbar navbar-inverse navbar-statick-top nav-color'>
      <ul class='nav navbar-nav '>
        <a class="navbar-brand glyphicon glyphicon-piggy-bank eikona" href="#"></a>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:index' %}">Αρχική</a></li>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:employee_list' %}">Υπάλληλοι</a></li>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:posto_list' %}">Πόστα</a></li>
        <li><a class = 'navbar-link' href="{% url 'diaxoristis:tip_list' %}">Tips</a></li>
      </ul>

    </nav>




  <div class="blue_box">

          <h1>Διαχωριστής των Tips</h1>
          <h3>Ο εύκολος τρόπος να χωρίζεις τα tips με τους συναδέλφους σου!</h3>

          <h2><a class= 'btn btn-success btn-lg index_button' href="{% url 'diaxoristis:step_one' %}">Χώρισε τα Tips σου</a></h2>
  </div>











  </body>
</html>

Tips/diaxoristis/templates/diaxoristis/posto_confirm_delete.html
{% extends "base.html" %}

{% block body_block %}
<div class="jumbotron">


<h1>Διαγραφή {{posto.name}} ?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Διαγραφή">
  <a class="btn btn-warning" href="{% url 'diaxoristis:posto_list' %}">Άκυρο</a>

</form>

{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/posto_detail.html
{% extends "base.html" %}
{% block body_block%}
<div class="jumbotron">
  <h1>Detail Page!</h1>

  <div class="container">


  <div class="row">
    <table class="table table-bordered table table-hover">
      <tr>
        <col width="150">
        <col width="600">
        <th><h2>Όνομα</h2></th>
        <td><h3><a href="#">{{posto_detail.name}}</a></h3></td>
      </tr>

    </table>

  </div>
  </div>





  <div class="container">
      <p><a class= 'btn btn-success' href="{% url 'diaxoristis:posto_list' %}">Πίσω</a>

  </div>

{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/posto_list.html
{% extends "base.html" %}

{% block body_block%}
<div class="jumbotron">


<div class="container">
<h1>Πόστα!</h1>
<table class="table table-bordered table table-hover" >
  <tr>

    <col width="150">
    <col width="600">
    <th><h2>Όνομα</h2></th>

    <th width="600">                                 </th>

  </tr>



  {% for posto in posta %}


  <tr>
    <td><a class="col-md-8" href="{% url 'diaxoristis:posto_detail' pk=posto.id %}"><h3>{{posto.name}}</h3></a></td>

    <td  width="1000">
  <h2><a class= 'btn btn-warning' href="{% url 'diaxoristis:posto_update' pk=posto.id %}">Επεξεργασία</a>

  <a class= 'btn btn-danger' href="{% url 'diaxoristis:posto_delete' pk=posto.id %}">Διαγαφή</a></h2>
    </td></tr>
  {% endfor %}
</table>

<div class="row">
  <div class="col-xs-6 col-md-4">
      <h2><a class= 'btn btn-success' href="{% url 'diaxoristis:posto_create' %}">Δημιουργία</a></h2>
  </div>
  <div class="col-xs-6 col-md-4"></div>
  <div class="col-xs-6 col-md-4">

  </div>
</div>

</div>


{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/step_one.html
{% extends "base.html" %}
{% block body_block%}
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" style="width: 33%">
    <span class="sr-only">33% Complete</span>
  </div>
</div>

<div class="jumbotron">
  <h1>Πρώτο Βήμα!</h1>

<div class="container">

  <form  method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" class="btn btn-success" value="Βήμα 2 ->">
  </form>

</div>



{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/step_three.html
{% extends "base.html" %}
{% load costum_filter_tags %}
{% block body_block%}
<div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="3" style="width: 100%">
    <span class="sr-only">100% Complete</span>
  </div>
</div>

<div class="jumbotron">
  <h1>Τρίτο Βήμα!</h1>

  <div class="container">
    <div class="panel panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title"> Αποτέλεσμα διαχωρισμού των Tips</h3>
    </div>
    <div class="panel-body">
      <p>Πόστο: {{context.result.posto}} </p>
      <p>Συνολικά Μεροκάματα : {{context.result.merokamata}} </p>
      <p>Χρήματα ανα μεροκάματο : {{context.result.merokamato}} €</p>
      <p>Tips από : {{context.result.date_from|date:'d-m-Y'}}</p>
      <p>Tips μέχρι : {{context.result.date_until|date:'d-m-Y'}}</p>

      {% if  context.result.ypoloipo < 0 %}
      <div class="panel panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"> Προσοχή </h3>
      </div>
      <div class="panel-body">
        <p> Με τη στρογγυλοποίηση των μεταβλητών το ποσό που μοιράστηκε είναι μεγαλύτερο και χρειαζόμαστε ακόμα άλλα {{ context.result.ypoloipo|multi }} ευρώ για να είμαστε σωστοί με το άθροισμα.</p>
        <p> Παρακαλώ ελέγξτε τις καταχωρήσεις σας!!!</p>
      </div>


      {% elif  context.result.ypoloipo > 0 %}
      <div class="panel panel panel-warning">
      <div class="panel-heading">
        <h3 class="panel-title"> Προσοχή </h3>
      </div>
      <div class="panel-body">
      <p>Το υπόλοιπο είναι {{ context.result.ypoloipo }} ευρώ.</p>
      </div>

      {% else %}
      <div class="panel panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title"></h3>
      </div>
      <div class="panel-body">
      <p>Δεν υπάρχει υπόλοιπο.</p>
      </div>

      {% endif %}



    </div>
    </div>


  </div>

{% for yp in context.result.ypalliloi %}

<div class="panel panel panel-primary">
<div class="panel-heading">
  <h3 class="panel-title">{{ yp.name }}</h3>
</div>
<div class="panel-body">
  <p>Μεροκάματα : {{yp.merokamata}} </p>
  <p>Δικαιούται : {{yp.money}} €</p>
</div>
</div>


{% endfor %}
<div class="container">



      <h2><a class= 'btn btn-success' href="{% url 'diaxoristis:index' %}">Αρχική</a></h2>



      {% csrf_token%}
      <form action="{% url 'diaxoristis:step_three' %}" method="GET">
        <input class= 'btn btn-warning' type="Submit"  name="submit" value="Αποθήκευση"/>
      </form>




</div>
{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/tip_confirm_delete.html
{% extends "base.html" %}

{% block body_block %}

<div class="jumbotron">


<h1>Διαγραφή {{tip.start_date}} ?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Διαγραφή">
  <a class="btn btn-warning" href="{% url 'diaxoristis:tip_list'%}">Άκυρο</a>

</form>

{% endblock %}
</div>

Tips/diaxoristis/templates/diaxoristis/tip_detail.html
{% extends "base.html" %}
{% block body_block%}
<div class="jumbotron">
  <h1>Ιστορικό των Tips!</h1>


  <div class="container">


  <div class="row">
    <table class="table table-bordered table table-hover">
      <tr>
        <col width="150">
        <col width="600">
        <th><h2>Από</h2></th>
        <td><h3><a href="#">{{tips_detail.start_date|date:'d-m-Y'}}</a></h3></td>
      </tr>
      <tr>
        <th><h2>Έως</h2></th>
        <td><h3><a href="#">{{tips_detail.end_date|date:'d-m-Y'}}</a></h3></td>
      </tr>
      <tr>
        <th><h2>Χρήματα</h2></th>
        <td><h3><a href="#">{{tips_detail.money}}</a></h3></td>
      </tr>

    </table>

  </div>
  </div>


    <div class="container">
        <p><a class= 'btn btn-success' href="{% url 'diaxoristis:tip_list' %}">Πίσω</a>

    </div>

  </div>

{% endblock %}

Tips/diaxoristis/templates/diaxoristis/tip_form.html
{% extends "base.html" %}
{% block body_block%}

<div class="container">


<h1>
{% if not form.instance.pk%}
Δημιουργία Tip
{% else %}
Ενημέρωση Tip
{% endif %}
</h1>

<form method="post">
  {% csrf_token%}
  {{ form.as_p}}
  <input type="submit" class="btn btn-success" value="Αποθήκευση">

</form>
</div>


{% endblock %}

Tips/diaxoristis/templates/diaxoristis/tip_list.html
{% extends "base.html" %}

{% block body_block%}
<div class="jumbotron">


<h1>Ιστορικό των Tips!</h1>
<table class="table table-bordered table table-hover" >
  <tr>

    <col width="150">
    <col width="600">
    <th><h2> Ημερομηνία (από) :</h2></th>

    <th width="600">                                 </th>

  </tr>

  {% for tip in tips %}



  <tr>
    <td width="1000"><a class="col-md-8" href="{{tip.id}}"><h3>{{tip.start_date|date:'d-m-Y'}}</h3></a></td>

    <td >


  <a class= 'btn btn-danger' href="{% url 'diaxoristis:tip_delete' pk=tip.id %}">Διαγαφή</a></h2>
    </td></tr>
  {% endfor %}
</table>


{% endblock %}
</div>